### ISSUE TITLE
linking problem

### ISSUE THREAD

**Issue by calber** [yixia/Vitamio-iOS#2]
I tryed to build the demo but I run into the following prob:
ld: warning: ignoring file ../Vitamio/libVitamio.a, file was built for archive which is not the architecture being linked (i386): ../Vitamio/libVitamio.a
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_VMediaPlayer", referenced from:
      objc-class-ref in PlayerController.o
  "_OBJC_CLASS_$_Vitamio", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mqlsq** [comment]
Can not run in the simulator,you try build on an iPhone.

**Comment by EchoLiao** [comment]
It is not support simulator(i386) in release v1.0.0, try to build with device.

**Comment by purepure** [comment]
I am using the newest 1.1.3 and its demo can run on simulator, but when I integrate into my application, it still get this error
Undefined symbols for architecture i386:
  "_iconv", referenced from:
      _avcodec_decode_subtitle2 in libffmpeg.a(utils.o)
  "_iconv_close", referenced from:
      _avcodec_decode_subtitle2 in libffmpeg.a(utils.o)
      _avcodec_open2 in libffmpeg.a(utils.o)
  "_iconv_open", referenced from:
      _avcodec_decode_subtitle2 in libffmpeg.a(utils.o)
      _avcodec_open2 in libffmpeg.a(utils.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I try to run on simulator. Please help to figure out
