### ISSUE TITLE
The latest version(1.1.3) get error but version 1.1.0 is not

### ISSUE THREAD

**Issue by purepure** [yixia/Vitamio-iOS#9]
I run code from your latest version but always get this error:

ld: warning: directory not found for option '-L/mydirectory/Vitamio-iOS-1.1.3/Vitamio'
Undefined symbols for architecture i386:
  "_iconv", referenced from:
      _avcodec_decode_subtitle2 in libffmpeg.a(utils.o)
  "_iconv_close", referenced from:
      _avcodec_decode_subtitle2 in libffmpeg.a(utils.o)
      _avcodec_open2 in libffmpeg.a(utils.o)
  "_iconv_open", referenced from:
      _avcodec_decode_subtitle2 in libffmpeg.a(utils.o)
      _avcodec_open2 in libffmpeg.a(utils.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It mean your lib missed some assets(_iconv, _iconv_close,..). Please verify your library. Maybe when your packed that lib, your don't clear your workspace,...
Many developer get this error. Please check because if not, no one can use your libs.

I try to use version 1.1 and don't get this error. It is wired, right?

**Comment by EchoLiao** [comment]
Add libiconv.dylib

**Comment by purepure** [comment]
Thank, it work !
(but in the document, i don't see any line about that lib)
Anyway, it work now, thank so much

**Comment by EchoLiao** [comment]
Docnuments, https://github.com/yixia/Vitamio-iOS/blob/master/Doc/Vitamio_SDK_for_iOS_User_Manual.md#add-system-framwork
